#
# Edit by ringo 19980606
# 19990723
#
#
#

CC = gcc

#加入mysql資料庫功能
CFLAGS=-march=x86-64 -w -O3 -pipe -freg-struct-return -minline-all-stringops -mmmx -msse -msse2 -I /Users/fanminjian/Downloads/mysql-5.5.28-osx10.6-x86_64/include/ $(INCFLAGS)
MYSQL=-L /Users/fanminjian/Downloads/mysql-5.5.28-osx10.6-x86_64/lib/mysql -lmysqlclient -lz -lm -I./

TOP=../..
PROG = saac
SHELL = /bin/sh
PERL=/usr/bin/perl

RPCGEN=${TOP}/bin/lsgen.perl

RPCHTML = ${TOP}/doc/saacproto.html
#RPCSRC = saacproto_serv.c saacproto_util.c saacproto_work.c saacproto_sup.c saacproto_lserver.c saacproto_oac.c deathcontend.c
RPCSRC = saacproto_serv.c saacproto_util.c saacproto_work.c saacproto_lserver.c saacproto_oac.c deathcontend.c
RPCINCLUDE = saacproto_serv.h saacproto_util.h saacproto_work.h saacproto_lserver.h saacproto_oac.h deathcontend.h
RPCNOUSE = saacproto_cli.c saacproto_cli.h

#加入mysql資料庫功能
SRC = main.c recv.c util.c char.c db.c mail.c acfamily.c defend.c lock.c tcpip_util.c chatroom.c auction.c sasql.c $(RPCSRC)
#SRC = main.c recv.c util.c char.c db.c mail.c acfamily.c defend.c lock.c tcpip_util.c chatroom.c auction.c $(RPCSRC)
OBJ =${SRC:.c=.o}

WKDIR=wk
WK=wk/acwk




all : ${PROG} ${WK}


${PROG} : $(RPCSRC) ${OBJ} 
	$(CC) $(CFLAGS) -o $(PROG) $(OBJ) $(MYSQL) 

${WK} :
	make -C ${WKDIR} all

depend: $(RPCSRC)
	mv makefile makefile.bak
	sed -ne '1,/^# DO NOT DELETE THIS LINE/p' makefile.bak > makefile
	cc -M -I /Users/fanminjian/Downloads/mysql-5.5.28-osx10.6-x86_64/include/ $(SRC) >> makefile 

clean:
	make -C ${WKDIR} clean;
	/bin/rm -f $(OBJ)
	/bin/rm -f *~
	/bin/rm -f stderr.*

distclean:
	/bin/rm -f $(PROG)
	/bin/rm -f $(RPCSRC) $(RPCINCLUDE) $(RPCNOUSE)
	${MAKE} clean

	mv makefile makefile.bak
	sed -ne '1,/^# DO NOT DELETE THIS LINE/p' makefile.bak > makefile
	/bin/rm -f makefile.bak

${RPCSRC} $(RPCINCLUDE): #${RPCHTML} ${RPCGEN}
#	$(PERL) ${RPCGEN} -euc ${RPCHTML} -h . -o .
#	rm -f ${RPCNOUSE}


rpc : ${RPCHTML} ${RPCGEN}
	$(PERL) ${RPCGEN} ${RPCHTML} -h . -o .
	rm -f ${RPCNOUSE}



# DO NOT DELETE THIS LINE
main.o: main.c main.h /usr/include/stdio.h /usr/include/sys/cdefs.h \
  /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/Availability.h \
  /usr/include/AvailabilityInternal.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/secure/_stdio.h \
  /usr/include/secure/_common.h /usr/include/stdlib.h \
  /usr/include/sys/wait.h /usr/include/sys/signal.h \
  /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h \
  /usr/include/i386/signal.h /usr/include/i386/_structs.h \
  /usr/include/sys/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/unistd.h \
  /usr/include/sys/unistd.h /usr/include/sys/select.h \
  /usr/include/sys/_select.h /usr/include/strings.h \
  /usr/include/string.h /usr/include/secure/_string.h \
  /usr/include/time.h /usr/include/_structs.h /usr/include/sys/time.h \
  /usr/include/errno.h /usr/include/sys/errno.h version.h util.h mail.h \
  db.h saacproto_util.h saacproto_serv.h acfamily.h \
  /usr/include/signal.h /usr/include/getopt.h /usr/include/fcntl.h \
  /usr/include/sys/fcntl.h /usr/include/netinet/tcp.h saacproto_work.h \
  lock.h recv.h defend.h char.h
recv.o: recv.c version.h main.h /usr/include/stdio.h \
  /usr/include/sys/cdefs.h /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/Availability.h \
  /usr/include/AvailabilityInternal.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/secure/_stdio.h \
  /usr/include/secure/_common.h /usr/include/stdlib.h \
  /usr/include/sys/wait.h /usr/include/sys/signal.h \
  /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h \
  /usr/include/i386/signal.h /usr/include/i386/_structs.h \
  /usr/include/sys/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/unistd.h \
  /usr/include/sys/unistd.h /usr/include/sys/select.h \
  /usr/include/sys/_select.h /usr/include/strings.h \
  /usr/include/string.h /usr/include/secure/_string.h \
  /usr/include/time.h /usr/include/_structs.h /usr/include/sys/time.h \
  /usr/include/errno.h /usr/include/sys/errno.h saacproto_util.h \
  saacproto_serv.h saacproto_lserver.h saacproto_work.h recv.h char.h \
  db.h mail.h lock.h util.h sasql.h acfamily.h defend.h
util.o: util.c /usr/include/unistd.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/sys/cdefs.h \
  /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/sys/unistd.h \
  /usr/include/Availability.h /usr/include/AvailabilityInternal.h \
  /usr/include/sys/select.h /usr/include/sys/appleapiopts.h \
  /usr/include/sys/_structs.h /usr/include/sys/_select.h \
  /usr/include/sys/stat.h /usr/include/errno.h /usr/include/sys/errno.h \
  main.h /usr/include/stdio.h /usr/include/secure/_stdio.h \
  /usr/include/secure/_common.h /usr/include/stdlib.h \
  /usr/include/sys/wait.h /usr/include/sys/signal.h \
  /usr/include/machine/signal.h /usr/include/i386/signal.h \
  /usr/include/i386/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/strings.h \
  /usr/include/string.h /usr/include/secure/_string.h \
  /usr/include/time.h /usr/include/_structs.h /usr/include/sys/time.h \
  version.h util.h
char.o: char.c /usr/include/time.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/sys/cdefs.h \
  /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/_structs.h \
  /usr/include/sys/_structs.h /usr/include/stdio.h \
  /usr/include/Availability.h /usr/include/AvailabilityInternal.h \
  /usr/include/secure/_stdio.h /usr/include/secure/_common.h \
  /usr/include/sys/types.h /usr/include/sys/appleapiopts.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/sys/stat.h \
  /usr/include/fcntl.h /usr/include/sys/fcntl.h /usr/include/unistd.h \
  /usr/include/sys/unistd.h /usr/include/sys/select.h \
  /usr/include/sys/_select.h main.h /usr/include/stdlib.h \
  /usr/include/sys/wait.h /usr/include/sys/signal.h \
  /usr/include/machine/signal.h /usr/include/i386/signal.h \
  /usr/include/i386/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/alloca.h /usr/include/netinet/in.h \
  /usr/bin/../lib/clang/4.1/include/stdint.h /usr/include/stdint.h \
  /usr/include/sys/socket.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/strings.h \
  /usr/include/string.h /usr/include/secure/_string.h \
  /usr/include/sys/time.h /usr/include/errno.h /usr/include/sys/errno.h \
  version.h char.h saacproto_serv.h saacproto_util.h util.h \
  saacproto_lserver.h acfamily.h lock.h recv.h sasql.h
db.o: db.c db.h main.h /usr/include/stdio.h /usr/include/sys/cdefs.h \
  /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/Availability.h \
  /usr/include/AvailabilityInternal.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/secure/_stdio.h \
  /usr/include/secure/_common.h /usr/include/stdlib.h \
  /usr/include/sys/wait.h /usr/include/sys/signal.h \
  /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h \
  /usr/include/i386/signal.h /usr/include/i386/_structs.h \
  /usr/include/sys/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/unistd.h \
  /usr/include/sys/unistd.h /usr/include/sys/select.h \
  /usr/include/sys/_select.h /usr/include/strings.h \
  /usr/include/string.h /usr/include/secure/_string.h \
  /usr/include/time.h /usr/include/_structs.h /usr/include/sys/time.h \
  /usr/include/errno.h /usr/include/sys/errno.h version.h util.h \
  /usr/include/dirent.h /usr/include/sys/dirent.h \
  /usr/include/sys/stat.h
mail.o: mail.c main.h /usr/include/stdio.h /usr/include/sys/cdefs.h \
  /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/Availability.h \
  /usr/include/AvailabilityInternal.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/secure/_stdio.h \
  /usr/include/secure/_common.h /usr/include/stdlib.h \
  /usr/include/sys/wait.h /usr/include/sys/signal.h \
  /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h \
  /usr/include/i386/signal.h /usr/include/i386/_structs.h \
  /usr/include/sys/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/unistd.h \
  /usr/include/sys/unistd.h /usr/include/sys/select.h \
  /usr/include/sys/_select.h /usr/include/strings.h \
  /usr/include/string.h /usr/include/secure/_string.h \
  /usr/include/time.h /usr/include/_structs.h /usr/include/sys/time.h \
  /usr/include/errno.h /usr/include/sys/errno.h version.h mail.h util.h \
  saacproto_serv.h saacproto_util.h /usr/include/dirent.h \
  /usr/include/sys/dirent.h /usr/include/sys/stat.h
acfamily.o: acfamily.c version.h main.h /usr/include/stdio.h \
  /usr/include/sys/cdefs.h /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/Availability.h \
  /usr/include/AvailabilityInternal.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/secure/_stdio.h \
  /usr/include/secure/_common.h /usr/include/stdlib.h \
  /usr/include/sys/wait.h /usr/include/sys/signal.h \
  /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h \
  /usr/include/i386/signal.h /usr/include/i386/_structs.h \
  /usr/include/sys/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/unistd.h \
  /usr/include/sys/unistd.h /usr/include/sys/select.h \
  /usr/include/sys/_select.h /usr/include/strings.h \
  /usr/include/string.h /usr/include/secure/_string.h \
  /usr/include/time.h /usr/include/_structs.h /usr/include/sys/time.h \
  /usr/include/errno.h /usr/include/sys/errno.h acfamily.h util.h \
  saacproto_serv.h saacproto_util.h /usr/include/dirent.h \
  /usr/include/sys/dirent.h /usr/include/sys/stat.h
defend.o: defend.c version.h /usr/include/stdio.h \
  /usr/include/sys/cdefs.h /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/Availability.h \
  /usr/include/AvailabilityInternal.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/secure/_stdio.h \
  /usr/include/secure/_common.h /usr/include/string.h \
  /usr/include/strings.h /usr/include/secure/_string.h \
  /usr/include/ctype.h /usr/include/runetype.h /usr/include/time.h \
  /usr/include/_structs.h /usr/include/sys/_structs.h saacproto_serv.h \
  saacproto_util.h /usr/include/stdlib.h /usr/include/sys/wait.h \
  /usr/include/sys/signal.h /usr/include/sys/appleapiopts.h \
  /usr/include/machine/signal.h /usr/include/i386/signal.h \
  /usr/include/i386/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/unistd.h /usr/include/sys/unistd.h \
  /usr/include/sys/select.h /usr/include/sys/_select.h main.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/sys/time.h \
  /usr/include/errno.h /usr/include/sys/errno.h char.h util.h defend.h
lock.o: lock.c /usr/include/stdio.h /usr/include/sys/cdefs.h \
  /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/Availability.h \
  /usr/include/AvailabilityInternal.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/secure/_stdio.h \
  /usr/include/secure/_common.h /usr/include/stdlib.h \
  /usr/include/sys/wait.h /usr/include/sys/signal.h \
  /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h \
  /usr/include/i386/signal.h /usr/include/i386/_structs.h \
  /usr/include/sys/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h lock.h \
  version.h main.h /usr/include/netinet/in.h \
  /usr/bin/../lib/clang/4.1/include/stdint.h /usr/include/stdint.h \
  /usr/include/sys/socket.h /usr/include/sys/types.h \
  /usr/include/machine/_param.h /usr/include/i386/_param.h \
  /usr/include/netinet6/in6.h /usr/include/arpa/inet.h \
  /usr/include/netdb.h /usr/include/unistd.h /usr/include/sys/unistd.h \
  /usr/include/sys/select.h /usr/include/sys/_select.h \
  /usr/include/strings.h /usr/include/string.h \
  /usr/include/secure/_string.h /usr/include/time.h \
  /usr/include/_structs.h /usr/include/sys/time.h /usr/include/errno.h \
  /usr/include/sys/errno.h char.h recv.h
tcpip_util.o: tcpip_util.c version.h main.h /usr/include/stdio.h \
  /usr/include/sys/cdefs.h /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/Availability.h \
  /usr/include/AvailabilityInternal.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/secure/_stdio.h \
  /usr/include/secure/_common.h /usr/include/stdlib.h \
  /usr/include/sys/wait.h /usr/include/sys/signal.h \
  /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h \
  /usr/include/i386/signal.h /usr/include/i386/_structs.h \
  /usr/include/sys/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/unistd.h \
  /usr/include/sys/unistd.h /usr/include/sys/select.h \
  /usr/include/sys/_select.h /usr/include/strings.h \
  /usr/include/string.h /usr/include/secure/_string.h \
  /usr/include/time.h /usr/include/_structs.h /usr/include/sys/time.h \
  /usr/include/errno.h /usr/include/sys/errno.h tcpip_util.h
chatroom.o: chatroom.c version.h main.h /usr/include/stdio.h \
  /usr/include/sys/cdefs.h /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/Availability.h \
  /usr/include/AvailabilityInternal.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/secure/_stdio.h \
  /usr/include/secure/_common.h /usr/include/stdlib.h \
  /usr/include/sys/wait.h /usr/include/sys/signal.h \
  /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h \
  /usr/include/i386/signal.h /usr/include/i386/_structs.h \
  /usr/include/sys/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/unistd.h \
  /usr/include/sys/unistd.h /usr/include/sys/select.h \
  /usr/include/sys/_select.h /usr/include/strings.h \
  /usr/include/string.h /usr/include/secure/_string.h \
  /usr/include/time.h /usr/include/_structs.h /usr/include/sys/time.h \
  /usr/include/errno.h /usr/include/sys/errno.h util.h saacproto_serv.h \
  saacproto_util.h
auction.o: auction.c version.h
sasql.o: sasql.c version.h main.h /usr/include/stdio.h \
  /usr/include/sys/cdefs.h /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/Availability.h \
  /usr/include/AvailabilityInternal.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/secure/_stdio.h \
  /usr/include/secure/_common.h /usr/include/stdlib.h \
  /usr/include/sys/wait.h /usr/include/sys/signal.h \
  /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h \
  /usr/include/i386/signal.h /usr/include/i386/_structs.h \
  /usr/include/sys/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/unistd.h \
  /usr/include/sys/unistd.h /usr/include/sys/select.h \
  /usr/include/sys/_select.h /usr/include/strings.h \
  /usr/include/string.h /usr/include/secure/_string.h \
  /usr/include/time.h /usr/include/_structs.h /usr/include/sys/time.h \
  /usr/include/errno.h /usr/include/sys/errno.h util.h mail.h db.h \
  saacproto_util.h saacproto_serv.h acfamily.h /usr/include/signal.h \
  /usr/include/getopt.h /usr/include/fcntl.h /usr/include/sys/fcntl.h \
  /usr/include/netinet/tcp.h saacproto_work.h lock.h recv.h defend.h \
  char.h \
  /Users/fanminjian/Downloads/mysql-5.5.28-osx10.6-x86_64/include/mysql.h \
  /Users/fanminjian/Downloads/mysql-5.5.28-osx10.6-x86_64/include/mysql_version.h \
  /Users/fanminjian/Downloads/mysql-5.5.28-osx10.6-x86_64/include/mysql_com.h \
  /Users/fanminjian/Downloads/mysql-5.5.28-osx10.6-x86_64/include/mysql_time.h \
  /Users/fanminjian/Downloads/mysql-5.5.28-osx10.6-x86_64/include/my_list.h \
  /Users/fanminjian/Downloads/mysql-5.5.28-osx10.6-x86_64/include/typelib.h \
  /Users/fanminjian/Downloads/mysql-5.5.28-osx10.6-x86_64/include/my_alloc.h
saacproto_serv.o: saacproto_serv.c version.h saacproto_serv.h \
  saacproto_util.h /usr/include/stdlib.h /usr/include/Availability.h \
  /usr/include/AvailabilityInternal.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/sys/cdefs.h \
  /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/sys/wait.h \
  /usr/include/sys/signal.h /usr/include/sys/appleapiopts.h \
  /usr/include/machine/signal.h /usr/include/i386/signal.h \
  /usr/include/i386/_structs.h /usr/include/sys/_structs.h \
  /usr/include/machine/_structs.h /usr/include/mach/i386/_structs.h \
  /usr/include/sys/resource.h /usr/include/machine/endian.h \
  /usr/include/i386/endian.h /usr/include/sys/_endian.h \
  /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/string.h /usr/include/strings.h \
  /usr/include/secure/_string.h /usr/include/secure/_common.h \
  /usr/include/unistd.h /usr/include/sys/unistd.h \
  /usr/include/sys/select.h /usr/include/sys/_select.h main.h \
  /usr/include/stdio.h /usr/include/secure/_stdio.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/time.h \
  /usr/include/_structs.h /usr/include/sys/time.h /usr/include/errno.h \
  /usr/include/sys/errno.h
saacproto_util.o: saacproto_util.c version.h /usr/include/stdio.h \
  /usr/include/sys/cdefs.h /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/Availability.h \
  /usr/include/AvailabilityInternal.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/secure/_stdio.h \
  /usr/include/secure/_common.h /usr/include/stdlib.h \
  /usr/include/sys/wait.h /usr/include/sys/signal.h \
  /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h \
  /usr/include/i386/signal.h /usr/include/i386/_structs.h \
  /usr/include/sys/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/string.h /usr/include/strings.h \
  /usr/include/secure/_string.h /usr/include/unistd.h \
  /usr/include/sys/unistd.h /usr/include/sys/select.h \
  /usr/include/sys/_select.h main.h /usr/include/netinet/in.h \
  /usr/bin/../lib/clang/4.1/include/stdint.h /usr/include/stdint.h \
  /usr/include/sys/socket.h /usr/include/sys/types.h \
  /usr/include/machine/_param.h /usr/include/i386/_param.h \
  /usr/include/netinet6/in6.h /usr/include/arpa/inet.h \
  /usr/include/netdb.h /usr/include/time.h /usr/include/_structs.h \
  /usr/include/sys/time.h /usr/include/errno.h /usr/include/sys/errno.h \
  saacproto_util.h
saacproto_work.o: saacproto_work.c version.h main.h /usr/include/stdio.h \
  /usr/include/sys/cdefs.h /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/Availability.h \
  /usr/include/AvailabilityInternal.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/secure/_stdio.h \
  /usr/include/secure/_common.h /usr/include/stdlib.h \
  /usr/include/sys/wait.h /usr/include/sys/signal.h \
  /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h \
  /usr/include/i386/signal.h /usr/include/i386/_structs.h \
  /usr/include/sys/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/unistd.h \
  /usr/include/sys/unistd.h /usr/include/sys/select.h \
  /usr/include/sys/_select.h /usr/include/strings.h \
  /usr/include/string.h /usr/include/secure/_string.h \
  /usr/include/time.h /usr/include/_structs.h /usr/include/sys/time.h \
  /usr/include/errno.h /usr/include/sys/errno.h recv.h saacproto_serv.h \
  saacproto_util.h saacproto_work.h char.h
saacproto_lserver.o: saacproto_lserver.c saacproto_lserver.h version.h \
  saacproto_serv.h saacproto_util.h /usr/include/stdlib.h \
  /usr/include/Availability.h /usr/include/AvailabilityInternal.h \
  /usr/include/_types.h /usr/include/sys/_types.h \
  /usr/include/sys/cdefs.h /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/sys/wait.h \
  /usr/include/sys/signal.h /usr/include/sys/appleapiopts.h \
  /usr/include/machine/signal.h /usr/include/i386/signal.h \
  /usr/include/i386/_structs.h /usr/include/sys/_structs.h \
  /usr/include/machine/_structs.h /usr/include/mach/i386/_structs.h \
  /usr/include/sys/resource.h /usr/include/machine/endian.h \
  /usr/include/i386/endian.h /usr/include/sys/_endian.h \
  /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/string.h /usr/include/strings.h \
  /usr/include/secure/_string.h /usr/include/secure/_common.h \
  /usr/include/unistd.h /usr/include/sys/unistd.h \
  /usr/include/sys/select.h /usr/include/sys/_select.h main.h \
  /usr/include/stdio.h /usr/include/secure/_stdio.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/time.h \
  /usr/include/_structs.h /usr/include/sys/time.h /usr/include/errno.h \
  /usr/include/sys/errno.h char.h util.h
saacproto_oac.o: saacproto_oac.c version.h main.h /usr/include/stdio.h \
  /usr/include/sys/cdefs.h /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/Availability.h \
  /usr/include/AvailabilityInternal.h /usr/include/_types.h \
  /usr/include/sys/_types.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/secure/_stdio.h \
  /usr/include/secure/_common.h /usr/include/stdlib.h \
  /usr/include/sys/wait.h /usr/include/sys/signal.h \
  /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h \
  /usr/include/i386/signal.h /usr/include/i386/_structs.h \
  /usr/include/sys/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/unistd.h \
  /usr/include/sys/unistd.h /usr/include/sys/select.h \
  /usr/include/sys/_select.h /usr/include/strings.h \
  /usr/include/string.h /usr/include/secure/_string.h \
  /usr/include/time.h /usr/include/_structs.h /usr/include/sys/time.h \
  /usr/include/errno.h /usr/include/sys/errno.h util.h char.h \
  tcpip_util.h saacproto_util.h saacproto_oac.h
deathcontend.o: deathcontend.c version.h /usr/include/time.h \
  /usr/include/_types.h /usr/include/sys/_types.h \
  /usr/include/sys/cdefs.h /usr/include/sys/_symbol_aliasing.h \
  /usr/include/sys/_posix_availability.h /usr/include/machine/_types.h \
  /usr/include/i386/_types.h /usr/include/_structs.h \
  /usr/include/sys/_structs.h main.h /usr/include/stdio.h \
  /usr/include/Availability.h /usr/include/AvailabilityInternal.h \
  /usr/include/secure/_stdio.h /usr/include/secure/_common.h \
  /usr/include/stdlib.h /usr/include/sys/wait.h \
  /usr/include/sys/signal.h /usr/include/sys/appleapiopts.h \
  /usr/include/machine/signal.h /usr/include/i386/signal.h \
  /usr/include/i386/_structs.h /usr/include/machine/_structs.h \
  /usr/include/mach/i386/_structs.h /usr/include/sys/resource.h \
  /usr/include/machine/endian.h /usr/include/i386/endian.h \
  /usr/include/sys/_endian.h /usr/include/libkern/_OSByteOrder.h \
  /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h \
  /usr/include/machine/types.h /usr/include/i386/types.h \
  /usr/include/netinet/in.h /usr/bin/../lib/clang/4.1/include/stdint.h \
  /usr/include/stdint.h /usr/include/sys/socket.h \
  /usr/include/sys/types.h /usr/include/machine/_param.h \
  /usr/include/i386/_param.h /usr/include/netinet6/in6.h \
  /usr/include/arpa/inet.h /usr/include/netdb.h /usr/include/unistd.h \
  /usr/include/sys/unistd.h /usr/include/sys/select.h \
  /usr/include/sys/_select.h /usr/include/strings.h \
  /usr/include/string.h /usr/include/secure/_string.h \
  /usr/include/sys/time.h /usr/include/errno.h /usr/include/sys/errno.h \
  saacproto_util.h saacproto_serv.h recv.h char.h util.h deathcontend.h
